# Generated by Django 5.2.17 on 2026-09-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_eat_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eat',
            name='model_file_usdz',
            field=models.FileField(blank=True, null=True, upload_to='models_usdz/'),
        ),
    ]
