# Generated by Django 5.2.17 on 2026-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0006_eat_usdz_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
