# Generated by Django 6.1 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eat", "0007_alter_category_id_alter_eat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="🍽️", max_length=16),
        ),
    ]
